extern crate gcc;

use std::env::set_var;


fn main() {
    set_var("CC", "arm-none-eabi-gcc");

    gcc::Config::new()
        .define("ARM_MATH_CM0", Some("1"))
        .define("NRF51", Some("1"))
        .define("TARGET_M0", Some("1"))
        .define("TARGET_MCU_NORDIC_16K", Some("1"))
        .define("TARGET_MCU_NRF51822", Some("1"))
        .define("TARGET_NORDIC", Some("1"))
        .define("TARGET_NRF51822", Some("1"))
        .define("TARGET_NRF51822_MKIT", Some("1"))
        .define("TOOLCHAIN_GCC", Some("1"))
        .define("TOOLCHAIN_GCC_ARM", Some("1"))
        .define("__CORTEX_M0", Some("1"))
        .flag("-mcpu=cortex-m0")
        .flag("-march=armv6-m")
        .flag("-mthumb")
        .flag("-mabi=aapcs")
        .flag("-mfloat-abi=soft")
        .flag("-std=gnu99")
        .flag("-ffunction-sections")
        .flag("-fdata-sections")
        .flag("-fmessage-length=0")
        .flag("-fno-delete-null-pointer-checks")
        .flag("-fomit-frame-pointer")
        .flag("-funsigned-bitfields")
        .flag("-fno-common")
        .flag("-fno-builtin")
        .flag("-Os")
        .flag("-Wall")
        .flag("-Wextra")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-missing-field-initializers")
        .flag("-Wno-error=switch")
        .flag("-Wno-switch")
        .include("src")
        .include("third_party/nrf51_sdk/toolchain")
        .include("third_party/nrf51_sdk/toolchain/gcc")
        .include("third_party/nrf51_sdk/device")
        .include("third_party/nrf51_sdk/softdevice/s110/headers")
        .include("third_party/nrf51_sdk/softdevice/common/softdevice_handler")
        .include("third_party/nrf51_sdk/libraries/util")
        .include("third_party/nrf51_sdk/libraries/scheduler")
        .include("third_party/nrf51_sdk/libraries/timer")
        .include("third_party/nrf51_sdk/ble/ble_advertising")
        .include("third_party/nrf51_sdk/ble/common")
        .include("third_party/nrf51_sdk/libraries/trace")
        .include("third_party/nrf51_sdk/drivers_nrf/pstorage")
        .include("third_party/nrf51_sdk/drivers_nrf/pstorage/config")
        .include("third_party/nrf51_sdk/drivers_nrf/ble_flash")
        .include("third_party/nrf51_sdk/libraries/timer")
        .include("third_party/nrf51_sdk/drivers_nrf/delay")

        .target("arm-none-eabi")

        .file("third_party/nrf51_sdk/toolchain/system_nrf51.c")
        .file("third_party/nrf51_sdk/toolchain/gcc/gcc_startup_nrf51.s")
        .file("third_party/nrf51_sdk/softdevice/common/softdevice_handler/softdevice_handler.c")
        .file("third_party/nrf51_sdk/softdevice/common/softdevice_handler/softdevice_handler_appsh.c")
        .file("third_party/nrf51_sdk/ble/common/ble_advdata.c")
        .file("third_party/nrf51_sdk/ble/ble_advertising/ble_advertising.c")
        .file("third_party/nrf51_sdk/libraries/timer/app_timer.c")

        .file("src/test.c")
        .compile("libnrf51.a");
}
