[package]
name = "blumenplace"
version = "0.1.0"
authors = ["zolkko <zolkko@gmail.com>"]
build = "build.rs"
links = "libnrf51.a"

[dependencies]
rust-libcore = "0.0.3"
macro_svc_call = {path = "macro_svc_call"}

[build-dependencies]
gcc = "0.3"

